### PR TITLE
buiding a new body for conflict reponses

### LINKED ISSUE #900: Prober retry logic can trigger Rekor failure
**Description**

We use a retryable HTTP client to make requests to Rekor (https://github.com/sigstore/scaffolding/blob/main/cmd/prober/write.go#L155). There are certain cases where a retry will always fail - For example, if the request times out, but Rekor actually succeeded in creating the entry, as the retried request will fail with an "Entry Already Exists" error.

If this error is returned, then we need to create a new blob to sign.

### PR DESCRIPTION
**Pull request by javanlacerda**
Closes #900

#### Summary

It adds retries updating the body for Rekor writing requests when the response has 409 code. It means that the body has conflict, then we should create a new/different body for the request.

### CODE REVIEW

File: cmd/prober/write.go [hunk 1]
```diff
@@ -151,19 +169,12 @@ func rekorWriteEndpoint(ctx context.Context, cert *x509.Certificate, priv *ecdsa
 		verificationCounter.With(prometheus.Labels{verifiedLabel: verified}).Inc()
 	}()
 
-	body, err := rekorEntryRequest(cert, priv)
-	if err != nil {
-		return fmt.Errorf("rekor entry: %w", err)
+	resp, t, err := makeRekorRequest(cert, priv, hostPath)
+	// A new body should be created when it is conflicted
+	for resp.StatusCode == http.StatusConflict {
```
Comment (javanlacerda) [inline cmd/prober/write.go:174]: Does it make sense it be in a `while`? Or should I set a number of attempts ?

File: cmd/prober/write.go [hunk 2]
```diff
@@ -151,24 +168,23 @@ func rekorWriteEndpoint(ctx context.Context, cert *x509.Certificate, priv *ecdsa
...
+		if resp.StatusCode != http.StatusConflict {
+			break
+		}
+		resp, t, err = makeRekorRequest(cert, priv, hostPath)
+		if err != nil {
+			return fmt.Errorf("error adding entry: %w", err)
+		}
+		defer resp.Body.Close()
+	}
+	latency := time.Since(t).Milliseconds()
```
Comment (haydentherapper) [inline cmd/prober/write.go:187]: Can we record latency and response data for each request to Rekor? This would measure the total time for all requests.

File: cmd/prober/write.go [hunk 3]
```diff
@@ -151,24 +168,23 @@ func rekorWriteEndpoint(ctx context.Context, cert *x509.Certificate, priv *ecdsa
...
-	t := time.Now()
-	resp, err := retryableClient.Do(req)
-	latency := time.Since(t).Milliseconds()
+	resp, t, err := makeRekorRequest(cert, priv, hostPath)
 	if err != nil {
 		return fmt.Errorf("error adding entry: %w", err)
 	}
 	defer resp.Body.Close()
+	// A new body should be created when it is conflicted
+	for {
```
Comment (haydentherapper) [inline cmd/prober/write.go:177]: Can we put a reasonable limit, let's say 10, on this loop?

File: cmd/prober/write.go [hunk 4]
```diff
@@ -151,24 +168,23 @@ func rekorWriteEndpoint(ctx context.Context, cert *x509.Certificate, priv *ecdsa
...
-	if err != nil {
-		return fmt.Errorf("new request: %w", err)
-	}
-
-	setHeaders(req, "")
-
-	t := time.Now()
-	resp, err := retryableClient.Do(req)
-	latency := time.Since(t).Milliseconds()
+	resp, t, err := makeRekorRequest(cert, priv, hostPath)
```
Comment (haydentherapper) [inline cmd/prober/write.go:171]: Can we move this into the for loop?

File: cmd/prober/write.go [hunk 5]
```diff
@@ -139,6 +139,23 @@ func fulcioWriteEndpoint(ctx context.Context, priv *ecdsa.PrivateKey) (*x509.Cer
...
+	}
+	req, err := retryablehttp.NewRequest(http.MethodPost, hostPath, bytes.NewBuffer(body))
+	if err != nil {
+		return nil, t, fmt.Errorf("new request: %w", err)
+	}
+	setHeaders(req, "")
+
+	t = time.Now()
+	resp, err := retryableClient.Do(req)
+	return resp, t, err
```
Comment (haydentherapper) [inline cmd/prober/write.go:156]: I'd suggest returning the latency calculation `latency := time.Since(t).Milliseconds()` rather than the time object.

**Review by haydentherapper — CHANGES_REQUESTED** [review]

**Review by haydentherapper — APPROVED** [review]
Thanks!
